from __future__ import annotations
from abc import ABC, abstractmethod
from jinja2 import Environment, FileSystemLoader
from weasyprint import HTML
from typing import TYPE_CHECKING
from helpers.debugger.logger import AbstractLogger
from helpers.exceptions.pdf_exceptions import PDFGenerationException, ReportDataTransformationException
from datetime import datetime
import markdown

if TYPE_CHECKING:
    from application.services.user_service import PatientData

class AbstractPDFGeneratorAdapter(ABC):
    """Abstract adapter for generating PDF documents."""

    logger = AbstractLogger.get_instance()

    @classmethod
    def __transform_gender(cls, gender: str) -> str:
        """
        Transform gender representation.
        Args:
            gender (str): Original gender string.
        Returns:
            str: Transformed gender string.
        """
        match gender:
            case 'male':
                gender = 'Home'
            case 'female':
                gender = 'Dona'
            case _:
                gender = 'Altres'
        return gender
    
    @classmethod
    def __transform_date(cls, date_str: str) -> str:
        """
        Transform date string from ISO format to Catalan format.
        
        Args:
            date_str (str): Date string in ISO 8601 format (e.g., '2025-12-09T11:27:12.204643+00:00').
        
        Returns:
            str: Formatted date string as 'DD/MM/YYYY HH:MM:SS'.
        
        Raises:
            ReportDataTransformationException: If date parsing fails.
        """
        try:
            dt = datetime.fromisoformat(date_str)
            return dt.strftime('%d/%m/%Y %H:%M:%S')
        except ValueError as e:
            raise ReportDataTransformationException("Error al transformar la data del pacient.") from e

    @classmethod
    def _transform_patient_data(cls, patient_data: PatientData) -> dict:
        """Transform patient data into a serializable dictionary.

        Args:
            patient_data (PatientData): The patient data to transform.

        Returns:
            dict: The transformed patient data.
        """
        try:
            patient_data['patient']['role']['gender'] = cls.__transform_gender(patient_data['patient']['role']['gender'])
            for score in patient_data['scores']:
                score['completed_at'] = cls.__transform_date(score['completed_at'])
            for question in patient_data.get('questions', []):
                question['answered_at'] = cls.__transform_date(question['answered_at'])
            allowed_graphs = {"progress_composite", "question_metrics"}
            graph_files = patient_data.get('graph_files', [])
            patient_data['graph_files'] = [
                graph for graph in graph_files
                if graph.get('filename', '').split('.')[0] in allowed_graphs
            ]

            return patient_data
        except KeyError as e:
            raise ReportDataTransformationException("Error al transformar les dades del pacient.") from e
        except Exception as e:
            raise ReportDataTransformationException("Error inesperat al transformar les dades del pacient.") from e

    @abstractmethod
    def generate_patient_report(self, patient_data: PatientData, date: str, llm_summary: str, template_path: str = 'templates/patient_report.html') -> bytes:
        """
        Generate a PDF report for a patient.
        Args:
            patient_data (PatientData): Data of the patient to include in the report.
            date (str): Date for the report.
            llm_summary (str): Summary generated by LLM to include in the report.
            template_path (str): Path to the HTML template for the report.
        Returns:
            bytes: The generated PDF document as a byte stream.
        Raises:
            PDFGenerationException: If there is an error during PDF generation.
        """
        raise NotImplementedError
    
class PDFGeneratorAdapter(AbstractPDFGeneratorAdapter):
    """Concrete adapter for generating PDF documents."""

    __env = Environment(loader=FileSystemLoader('.'))
    __env.filters['markdown_to_html'] = lambda text: markdown.markdown(
        text, extensions=['extra', 'nl2br']
    ) if text else ""
    
    def generate_patient_report(self, patient_data: PatientData, date: str, llm_summary: str, template_path: str = 'templates/patient_report.html') -> bytes:
        try:
            template = self.__env.get_template(template_path)

            transformed_data = self._transform_patient_data(patient_data)

            html_out = template.render(
                data=transformed_data,
                data_informe=date,
                llm_summary=llm_summary
            )

            pdf_bytes = HTML(string=html_out).write_pdf()
        except ReportDataTransformationException as e:
            self.logger.error("Error transforming patient data for PDF generation", module="PDFGeneratorAdapter", error=e)
            raise e
        except Exception as e:
            self.logger.error("Error generating PDF report", module="PDFGeneratorAdapter", error=e)
            raise PDFGenerationException("Error al generar el PDF.") from e

        if not pdf_bytes:
            self.logger.error("Generated PDF is empty", module="PDFGeneratorAdapter")
            raise PDFGenerationException("Ha ocurregut un error en generar el PDF.")
        
        return pdf_bytes
