# 1. Usamos la imagen oficial de Python 3.13 (versión ligera 'slim')
FROM python:3.13-slim

# 2. Evita que Python genere archivos .pyc y permite ver los logs en tiempo real
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# 3. Establecemos el directorio de trabajo dentro del contenedor
WORKDIR /app

# 4. Copiamos PRIMERO los requerimientos (para aprovechar la caché de Docker)
COPY requirements.txt .

# 5. Instalamos las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# 6. Copiamos el resto del código de tu carpeta al contenedor
COPY . .

# 7. Exponemos el puerto 5000 (el estándar de Flask)
EXPOSE 5000

# 8. Comando para iniciar la app usando Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]