"""question_answers

Revision ID: ea712778b538
Revises: add_question_answer_analysis
Create Date: 2025-12-10 10:47:36.289883
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea712778b538'
down_revision = 'add_question_answer_analysis'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('doctor_patient_patient_email_fkey'), 'doctor_patient', type_='foreignkey')
    op.drop_constraint(op.f('doctor_patient_doctor_email_fkey'), 'doctor_patient', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_patient', 'patients', ['patient_email'], ['email'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'doctor_patient', 'doctors', ['doctor_email'], ['email'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('questions_answered', sa.Column('answer_text', sa.Text(), nullable=False))
    op.add_column('questions_answered', sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_constraint(op.f('questions_answered_patient_email_fkey'), 'questions_answered', type_='foreignkey')
    op.drop_constraint(op.f('questions_answered_question_id_fkey'), 'questions_answered', type_='foreignkey')
    op.create_foreign_key(None, 'questions_answered', 'questions', ['question_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'questions_answered', 'patients', ['patient_email'], ['email'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('scores_activity_id_fkey'), 'scores', type_='foreignkey')
    op.drop_constraint(op.f('scores_patient_email_fkey'), 'scores', type_='foreignkey')
    op.create_foreign_key(None, 'scores', 'patients', ['patient_email'], ['email'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'scores', 'activities', ['activity_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_transcription_chunks_session_index', 'transcription_chunks', ['session_id', 'chunk_index'], unique=False)
    op.create_unique_constraint('uq_transcription_chunks_session_chunk', 'transcription_chunks', ['session_id', 'chunk_index'])
    op.drop_constraint(op.f('user_codes_user_email_fkey'), 'user_codes', type_='foreignkey')
    op.create_foreign_key(None, 'user_codes', 'users', ['user_email'], ['email'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_codes', type_='foreignkey')
    op.create_foreign_key(op.f('user_codes_user_email_fkey'), 'user_codes', 'users', ['user_email'], ['email'], onupdate='CASCADE')
    op.drop_constraint('uq_transcription_chunks_session_chunk', 'transcription_chunks', type_='unique')
    op.drop_index('ix_transcription_chunks_session_index', table_name='transcription_chunks')
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.create_foreign_key(op.f('scores_patient_email_fkey'), 'scores', 'patients', ['patient_email'], ['email'], onupdate='CASCADE')
    op.create_foreign_key(op.f('scores_activity_id_fkey'), 'scores', 'activities', ['activity_id'], ['id'], onupdate='CASCADE')
    op.drop_constraint(None, 'questions_answered', type_='foreignkey')
    op.drop_constraint(None, 'questions_answered', type_='foreignkey')
    op.create_foreign_key(op.f('questions_answered_question_id_fkey'), 'questions_answered', 'questions', ['question_id'], ['id'], onupdate='CASCADE')
    op.create_foreign_key(op.f('questions_answered_patient_email_fkey'), 'questions_answered', 'patients', ['patient_email'], ['email'], onupdate='CASCADE')
    op.drop_column('questions_answered', 'analysis')
    op.drop_column('questions_answered', 'answer_text')
    op.drop_constraint(None, 'doctor_patient', type_='foreignkey')
    op.drop_constraint(None, 'doctor_patient', type_='foreignkey')
    op.create_foreign_key(op.f('doctor_patient_doctor_email_fkey'), 'doctor_patient', 'doctors', ['doctor_email'], ['email'], onupdate='CASCADE')
    op.create_foreign_key(op.f('doctor_patient_patient_email_fkey'), 'doctor_patient', 'patients', ['patient_email'], ['email'], onupdate='CASCADE')
    # ### end Alembic commands ###
